version: '2'

services:
  backend:
    image: 'encrypter:latest'
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    depends_on:
      - mongodb
    ports:
      - "8085:8085"
    environment:
      - SPRING_DB_HOST=mongodb
      - SPRING_DB_PORT=27017
      - SPRING_DATABASE=encrypter

  mongodb:
    image: 'mongo:4.4.3'
    restart: always
    ports:
      - "27017:27017"
    container_name: db
    volumes:
      - ./mongo-init.js:/docker-enrtypoint-initdb.d/mongo-init.js:ro