db:
  initFile:
    name: json/V1__init.json

spring:
  data:
    mongodb:
      database: ${SPRING_DATABASE:encrypter}
      host: ${SPRING_DB_HOST:localhost}
      port: ${SPRING_DB_PORT:27017}

server:
  port: 8085